export const APPLICATION_SUPPORT_CHECK = 'APPLICATION_SUPPORT_CHECK';
export const APPLICATION_INITIALIZE_CHECK = 'APPLICATION_INITIALIZE_CHECK';
export const APPLICATION_SERVER_CHECK = 'APPLICATION_SERVER_CHECK';
